---
# File: tasks/install.yml - package installation tasks for vault

- name: OS packages
  become: true
  package:
    name: "{{ vault_os_packages }}"
    state: present
    update_cache: true
  tags: installation
  when: (vault_os_packages is defined) and (vault_os_packages | length > 0)

# Temporary place for one-off version diff packages, etc.
- name: OS packages diff (Debian)
  become: true
  package:
    name: "libcap2-bin"
    state: present
  tags: installation
  when:
    - ansible_distribution == "Debian"
    - (ansible_distribution_version == 'buster/sid') or (ansible_distribution_version is version(8.5, '>'))

- name: Check Vault package file (local)
  stat:
    path: "{{ role_path }}/files/{{ vault_pkg }}"
  become: false
  run_once: true
  register: vault_package
  delegate_to: 127.0.0.1

- name: "Download Vault (local) â†’ {{ vault_zip_url }}"
  get_url:
    url: "{{ vault_zip_url }}"
    dest: "{{ role_path }}/files/{{ vault_pkg }}"
    checksum:
      "sha256:{{ (lookup('url', vault_checksum_file_url, wantlist=true) | select('match', '.*' + (vault_pkg | regex_escape()) + '$') | first).split()[0] }}"
    timeout: "42"
    mode: "0644"
  become: "{{ vault_privileged_install }}"
  run_once: true
  tags: installation
  when: not vault_package.stat.exists | bool
  delegate_to: 127.0.0.1

- name: Unarchive Vault (local)
  unarchive:
    src: "{{ role_path }}/files/{{ vault_pkg }}"
    dest: "{{ role_path }}/files/"
    creates: "{{ role_path }}/files/vault"
  become: "{{ vault_privileged_install }}"
  run_once: true
  tags: installation
  delegate_to: 127.0.0.1

- name: Install Vault
  become: true
  copy:
    src: "{{ role_path }}/files/vault"
    dest: "{{ vault_bin_path }}"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: "{{ vault_harden_file_perms | ternary('0555', '0755') }}"
  notify: Restart vault
  tags: installation

- name: Cleanup (local)
  file:
    path: "{{ item }}"
    state: "absent"
  become: "{{ vault_privileged_install }}"
  with_fileglob: "{{ role_path }}/files/vault"
  run_once: true
  tags: installation
  delegate_to: 127.0.0.1
